services:
  - type: web
    name: tech-mgmt-api
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npx prisma generate
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5001
      - key: CORS_ORIGIN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: tech-mgmt-db
          property: connectionString
    healthCheckPath: /api/v1/health

databases:
  - name: tech-mgmt-db
    region: oregon
    plan: starter
    databaseName: tech_mgmt_prod
    user: tech_mgmt_user
